// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFXpYAjqx34H4BKlHK-heHBPIwZmANZo0',
    appId: '1:987147458806:web:4479081c06f5685d90b4d7',
    messagingSenderId: '987147458806',
    projectId: 'itbsexpress-8ecbf',
    authDomain: 'itbsexpress-8ecbf.firebaseapp.com',
    storageBucket: 'itbsexpress-8ecbf.firebasestorage.app',
    measurementId: 'G-S5X7JS6PW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCULc07Tb3cdDHCXE5_xHNd49h-quyxw',
    appId: '1:987147458806:android:a29b2ee5c853ae2d90b4d7',
    messagingSenderId: '987147458806',
    projectId: 'itbsexpress-8ecbf',
    storageBucket: 'itbsexpress-8ecbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc58iFj8NyQqxl-eGFyL_6kGTA-Qvu4DE',
    appId: '1:987147458806:ios:3d1a79445361187a90b4d7',
    messagingSenderId: '987147458806',
    projectId: 'itbsexpress-8ecbf',
    storageBucket: 'itbsexpress-8ecbf.firebasestorage.app',
    iosBundleId: 'com.example.itbsExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc58iFj8NyQqxl-eGFyL_6kGTA-Qvu4DE',
    appId: '1:987147458806:ios:3d1a79445361187a90b4d7',
    messagingSenderId: '987147458806',
    projectId: 'itbsexpress-8ecbf',
    storageBucket: 'itbsexpress-8ecbf.firebasestorage.app',
    iosBundleId: 'com.example.itbsExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFXpYAjqx34H4BKlHK-heHBPIwZmANZo0',
    appId: '1:987147458806:web:fd7269e85a9653aa90b4d7',
    messagingSenderId: '987147458806',
    projectId: 'itbsexpress-8ecbf',
    authDomain: 'itbsexpress-8ecbf.firebaseapp.com',
    storageBucket: 'itbsexpress-8ecbf.firebasestorage.app',
    measurementId: 'G-LSZPRLEBHB',
  );
}
